//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapyCZforTS_CS.Localization {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapyCZforTS_CS.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Enable proxy.
        /// </summary>
        public static string ButtonEnableProxy {
            get {
                return ResourceManager.GetString("ButtonEnableProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Advanced logging.
        /// </summary>
        public static string CheckboxAdvancedLogging {
            get {
                return ResourceManager.GetString("CheckboxAdvancedLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Enable caching of map tiles.
        /// </summary>
        public static string CheckboxCaching {
            get {
                return ResourceManager.GetString("CheckboxCaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný checked.
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Oops, something went wrong while restoring proxy settings.\nPlease manually set these values:\nAddress: {0}\nPort: {1}\nExcluded adresses: {2}\nExlude localhost: {3}!.
        /// </summary>
        public static string ContentRestoreProxy {
            get {
                return ResourceManager.GetString("ContentRestoreProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Oops, something went wrong while setting proxy settings.\nPlease manually set these values:\nAddress: localhost\nPort: {0}\nExcluded adresses:\nExlude localhost: uncheck!.
        /// </summary>
        public static string ContentSetProxy {
            get {
                return ResourceManager.GetString("ContentSetProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný from left.
        /// </summary>
        public static string FromLeft {
            get {
                return ResourceManager.GetString("FromLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný from right.
        /// </summary>
        public static string FromRight {
            get {
                return ResourceManager.GetString("FromRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Clear local images cache.
        /// </summary>
        public static string LabelClearCache {
            get {
                return ResourceManager.GetString("LabelClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Open log file.
        /// </summary>
        public static string LabelOpenLog {
            get {
                return ResourceManager.GetString("LabelOpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Port:.
        /// </summary>
        public static string LabelPort {
            get {
                return ResourceManager.GetString("LabelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Mapsets selection:.
        /// </summary>
        public static string LabelSelectMapset {
            get {
                return ResourceManager.GetString("LabelSelectMapset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Base.
        /// </summary>
        public static string MapTypeBase {
            get {
                return ResourceManager.GetString("MapTypeBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Geographic.
        /// </summary>
        public static string MapTypeGeo {
            get {
                return ResourceManager.GetString("MapTypeGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Historical 1836-1852.
        /// </summary>
        public static string MapTypeHist {
            get {
                return ResourceManager.GetString("MapTypeHist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Aerial.
        /// </summary>
        public static string MapTypeOrto {
            get {
                return ResourceManager.GetString("MapTypeOrto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Aerial 2003.
        /// </summary>
        public static string MapTypeOrto2003 {
            get {
                return ResourceManager.GetString("MapTypeOrto2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Aerial 2006.
        /// </summary>
        public static string MapTypeOrto2006 {
            get {
                return ResourceManager.GetString("MapTypeOrto2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Aerial 2012.
        /// </summary>
        public static string MapTypeOrto2012 {
            get {
                return ResourceManager.GetString("MapTypeOrto2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Aerial 2015.
        /// </summary>
        public static string MapTypeOrto2015 {
            get {
                return ResourceManager.GetString("MapTypeOrto2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Aerial 2018.
        /// </summary>
        public static string MapTypeOrto2018 {
            get {
                return ResourceManager.GetString("MapTypeOrto2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Relief.
        /// </summary>
        public static string MapTypeRelief {
            get {
                return ResourceManager.GetString("MapTypeRelief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tourist.
        /// </summary>
        public static string MapTypeTourist {
            get {
                return ResourceManager.GetString("MapTypeTourist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Transport.
        /// </summary>
        public static string MapTypeTransport {
            get {
                return ResourceManager.GetString("MapTypeTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Winter.
        /// </summary>
        public static string MapTypeWinter {
            get {
                return ResourceManager.GetString("MapTypeWinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Max available zoom: {0}
        ///({1}. slider position {2}).
        /// </summary>
        public static string MaxZoom {
            get {
                return ResourceManager.GetString("MaxZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Main.
        /// </summary>
        public static string MenuMain {
            get {
                return ResourceManager.GetString("MenuMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unable to restore proxy settings.
        /// </summary>
        public static string TitleRestoreProxy {
            get {
                return ResourceManager.GetString("TitleRestoreProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unable to set proxy settings.
        /// </summary>
        public static string TitleSetProxy {
            get {
                return ResourceManager.GetString("TitleSetProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný unchecked.
        /// </summary>
        public static string Unchecked {
            get {
                return ResourceManager.GetString("Unchecked", resourceCulture);
            }
        }
    }
}
